# -*- coding: utf-8 -*-
"""library.sys.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GyWFHYbKVh3zDaN06jhktd0P7yqgTIgK
"""

# 📚A simple Library Management System using OOPS
# by Prabhnoor Kaur Rana 😄

class Library:
    def __init__(self):
        self.books = {
    "You Had Me at 'Hello World'": "available",
    "Why Code When You Can Cry?": "available",
    "Server down forever": "available",
    "Once Upon a Loop": "available",
    "Coding with tears": "available",
    "Error 404: Sleep Missing": "available",
    "Return 0 : My life story": "available",
    "The Lazy Programmer’s Guide": "available"
}

        self.borrowed_books = {}

    def show_books(self):
        print("\n📚 Books in Library:\n")
        for book, status in self.books.items():
            print(f"• {book} → [{status}]")
        print("\n📖 Don’t just look... borrow one maybe cutie?😍 ")

    def borrow_book(self):
        name = input("Enter your cute name: ")
        book = input("Enter the book name you want to borrow cutie: ")

        if book in self.books and self.books[book] == "available":
            self.books[book] = "borrowed"
            self.borrowed_books[book] = name
            print(f"✅ {name}, you borrowed '{book}' successfully! Take care of it like your phone 😆")
            print("❤️ don’t forget to return books or we will send book ghosts 👻📖")
        else:
            print("❌ Sorry, that book is not available or doesn’t exist. Maybe try scrolling reels instead 🤪")

    def return_book(self):
        name = input("Enter your name cutie: ")
        book = input("Enter the book name you want to return cutie: \n")

        if book in self.borrowed_books and self.borrowed_books[book] == name:
            self.books[book] = "available"
            del self.borrowed_books[book]
            print(f"📖 Thank you {name}! You returned '{book}'... finally! 😅")
            print("😎 Library gods are pleased with your honesty!😀")

        else:
            print("⚠️ Wrong details! Are you returning the right book or your homework? 🤭")

    def donate_book(self):
        book = input("Enter the book name you want to donate cutie: ")
        if book not in self.books:
            self.books[book] = "available"
            print(f"Wow! '{book}' donated successfully. You’re officially hero today⚡🦸🏻")
        else:
            print("📚 This book already exists. Library says: 'No repeats please!' 😅")

    def track_borrowed_books(self):
        print("\n📕 Borrowed Books:")
        if not self.borrowed_books:
            print("☹️ No books borrowed yet... everyone’s being too lazyyyy today 🦥")
        else:
            for book, name in self.borrowed_books.items():
                print(f"• '{book}' → borrowed by {name}")


def main():
    library = Library()

    while True:
        print("🌟🙏🏻“Welcome to The Knowledge Lounge📚 — warning ⚠️: reading may cause extreme intelligence!”🤯🌟\n")
        print("1️⃣ Show all books")
        print("2️⃣ Borrow a book")
        print("3️⃣ Return a book")
        print("4️⃣ Donate a book")
        print("5️⃣ Track borrowed books")
        print("6️⃣ Exit")

        choice = input("\nEnter your choice (1-6): ")

        if choice == "1":
            library.show_books()
        elif choice == "2":
            library.borrow_book()
        elif choice == "3":
            library.return_book()
        elif choice == "4":
            library.donate_book()
        elif choice == "5":
            library.track_borrowed_books()
        elif choice == "6":
            print("\n📕 Thanks for visiting! Come again — the books love attention and cute readers like you👀📚")
            print("🧠 Knowledge downloaded successfully! 🤣 Just don't forget to return before it expired! 😜\n")
            print("👋 Bye bye, see you soon buddy! 💫")
            break
        else:
            print("⚠️ Invalid choice! Maybe your brain needs a reboot 😂")

        choice = input("\nDo you want to continue? (Y/N): ").lower()
        if choice != 'y':
            print("\n📕 Thanks for visiting! Come again — the books love attention and cute readers like you👀📚")
            print("🧠 Knowledge downloaded successfully! 🤣 Just don't forget to return before it expired! 😜\n")
            print("👋 Bye bye, see you soon buddy! 💫")
            break


main()